// client/src/game/table/Table.tsx
import React, { FC, ReactElement } from 'react'
import './Table.css'
import { Grid } from '@material-ui/core'
import { Cards } from './Cards'
import { Draw, PlayerAction, SkippingTurn } from '../../models/playerAction'
import { PlayersTurnMessage } from '../../models/message'
import { sendGameMessage } from '../../api'
import { Card, getCardsAssetNumber, Suit } from '../../models/card'
import RedoIcon from '@material-ui/icons/Redo'

interface Props {
    gameActive: boolean
    playerName: string
    participating: boolean
    deckTop?: Card
    playerOnTurn?: string
    cards: Card[]
    colorChangedTo?: Suit
    isSkippingTurn: boolean
    shouldDraw: number
    cardsInDeck: string
}

export const Table: FC<Props> = (props: Props): ReactElement => {
    const sendPlayerAction = (action: PlayerAction): void => {
        const message: PlayersTurnMessage = {
            type: 'players_turn',
            action,
        }
        sendGameMessage(message)
    }

    const handleDeckClick = (): void => {
        if (props.isSkippingTurn) skipATurn()
        else drawCard()
    }

    const drawCard = (): void => {
        if (!props.participating) return

        const action: Draw = {
            action: 'draw',
        }
        sendPlayerAction(action)
    }

    const skipATurn = (): void => {
        if (!props.participating) return

        const action: SkippingTurn = {
            action: 'skipping_turn',
        }
        sendPlayerAction(action)
    }

    const getPlayedCards = (): ReactElement => {
        if (props.deckTop) return <img className="deck-card" src={`/cards/${getCardsAssetNumber(props.deckTop)}.png`}
                                       alt={`${props.deckTop.value} of ${props.deckTop.suit}s`}/>
        else return <img className="deck-card" src="/cards/0.png" alt="Deck"/>
    }

    const getDeck = (): ReactElement => {
        return (
            <>
                <img className="deck-card deck-top-card"
                     src={props.cardsInDeck === '0' ? '/cards/gray.png' : '/cards/0.png'} alt="deck"
                     onClick={handleDeckClick}/>
                {props.cardsInDeck !== '' && <div className="card-count">{props.cardsInDeck}</div>}
                {props.isSkippingTurn && <div className="action-overlay">SKIP<br/><RedoIcon/></div>}
                {props.shouldDraw !== 0 && <div className="action-overlay">DRAW<br/>{props.shouldDraw}</div>}
            </>
        )
    }

    const getSuitIcon = (suit: Suit): ReactElement => {
        switch (suit) {
            case 'Ball':
                return <img className="overlay-suit-icon" src="/suits/ball.svg" alt="balls"/>
            case 'Dick':
                return <img className="overlay-suit-icon" src="/suits/dick.svg" alt="dicks"/>
            case 'Green':
                return <img className="overlay-suit-icon" src="/suits/green.svg" alt="greens"/>
            case 'Heart':
                return <img className="overlay-suit-icon" src="/suits/heart.svg" alt="hearts"/>
        }
    }

    return (
        <div id="table" className={props.playerOnTurn === props.playerName ? 'active-table' : undefined}>
            <Grid className="decks" container spacing={4} justify="center">
                <Grid className="deck-overlay-container" item>
                    {getDeck()}
                </Grid>
                <Grid className="color-overlay-container" item>
                    {getPlayedCards()}
                    {props.colorChangedTo && <div className="color-overlay">{getSuitIcon(props.colorChangedTo)}</div>}
                </Grid>
            </Grid>
            <hr/>
            <Cards gameActive={props.gameActive} cards={props.cards} playerName={props.playerName}
                   playerOnTurn={props.playerOnTurn}
                   deckTop={props.deckTop} sendPlayerAction={sendPlayerAction}
                   isSkippingTurn={props.isSkippingTurn}/>
        </div>
    )
}

// client/src/app/game/components/table/table.component.ts
import { Component, EventEmitter, Input, OnChanges, Output } from '@angular/core'
import { Card, Suit } from '../../../models/card'
import { Draw, PlayerAction, SkippingTurn } from '../../../models/playerAction'
import { ChangeGameStateMessage, PlayersTurnMessage } from '../../../models/message'
import { GameService } from '../../game.service'
import { SettingsService } from '../../../settings/settings.service'

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss'],
})
export class TableComponent implements OnChanges {
  @Input() readonly gameActive?: boolean
  @Input() readonly playerName?: string
  @Input() readonly participating?: boolean
  @Input() readonly deckTop?: Card[]
  @Input() readonly playerOnTurn?: string
  @Input() readonly cards?: Card[]
  @Input() readonly colorChangedTo?: Suit
  @Input() readonly isSkippingTurn?: boolean
  @Input() readonly isWinner?: boolean
  @Input() readonly isLoser?: boolean
  @Input() readonly shouldDraw?: number
  @Input() readonly cardsInDeck?: string
  @Input() readonly playersCount?: number
  @Output() nameChange: EventEmitter<string> = new EventEmitter()
  reversedDeck?: Card[]
  cardBack = this.settingsService.getCardBack()

  constructor(
    private gameService: GameService,
    private settingsService: SettingsService,
    ) { }

  ngOnChanges(): void {
    this.reversedDeck = this.deckTop && [...this.deckTop].reverse()
  }

  handleDeckClick(): void {
    if (!this.participating) { return }

    if (!this.gameActive && this.participating && this.playersCount && this.playersCount >= 2) {
      const message: ChangeGameStateMessage = {
        type: 'change_game',
        active: true,
      }
      this.gameService.sendMessage(message)
      return
    }

    if (this.isSkippingTurn) {
      this.skipATurn()
    } else {
      this.drawCard()
    }
  }

  /**
   * Helps Angular decide whether to update a card in the deck by giving each card a unique key
   * @param index not used
   * @param card combines the value and suit to create a unique key
   */
  trackByCard(index: number, card: Card): string {
    return `${card.value}${card.suit}`
  }

  canShuffle(): boolean {
    return !this.gameActive && !!this.participating && !!this.playersCount && this.playersCount >= 2
  }

  private drawCard(): void {
    const action: Draw = {
      action: 'draw',
    }
    this.sendPlayerAction(action)
  }

  private skipATurn(): void {
    const action: SkippingTurn = {
      action: 'skipping_turn',
    }
    this.sendPlayerAction(action)
  }

  private sendPlayerAction(action: PlayerAction): void {
    const message: PlayersTurnMessage = {
      type: 'players_turn',
      action,
    }
    this.gameService.sendMessage(message)
  }
}

<div id="table" class="ion-padding ion-margin-horizontal"
     [class.active-table]="gameActive && playerOnTurn && playerOnTurn === playerName">
  <ion-grid>
    <ion-row class="ion-justify-content-center decks">
      <ion-col class="ion-padding-end ion-margin-end" size="auto">
        <div class="deck-overlay-container"
             [class.empty-deck]="cardsInDeck === '0'"
             [style.background-image]="'url(assets/cards/back/' + ((cardBack | async) || 1) + '.svg)'"
             role="button"
             (click)="handleDeckClick()"
        >
          <div *ngIf="cardsInDeck" class="card-count">{{cardsInDeck}}</div>
          <div *ngIf="isSkippingTurn && !canShuffle; else canDraw" class="action-overlay">{{'Game.skip' | translate}}<br/>
            <ion-icon name="arrow-redo-sharp"></ion-icon>
          </div>
          <ng-template #canDraw>
            <div *ngIf="shouldDraw !== 0 && !canShuffle; else canBeShuffled" class="action-overlay">
              {{'Game.draw' | translate}}<br/>{{shouldDraw}}</div>
          </ng-template>
          <ng-template #canBeShuffled>
            <div *ngIf="canShuffle" class="action-overlay">{{'Game.shuffle' | translate}}<br/>
              <ion-icon name="shuffle"></ion-icon>
            </div>
          </ng-template>
        </div>
      </ion-col>
      <ion-col class="ion-padding-start ion-margin-start" size="auto">
        <div *ngIf="reversedDeck; else deckOutline">
          <app-deck-card
            [card]="reversedDeck[0]"
            [noTransform]="true"
            [colorChangedTo]="reversedDeck[0].value === 'Queen' ? colorChangedTo : undefined"
          ></app-deck-card>
          <app-deck-card
            *ngFor="let card of reversedDeck | slice:1; trackBy: trackByCard"
            [card]="card"
            [colorChangedTo]="card.value === 'Queen' ? colorChangedTo : undefined"
          ></app-deck-card>
        </div>
        <ng-template #deckOutline>
          <div class="deck-outline"></div>
        </ng-template>
      </ion-col>
    </ion-row>
  </ion-grid>
  <app-cards
    [participating]="participating"
    [gameActive]="gameActive"
    [cards]="cards"
    [playerName]="playerName"
    [playerOnTurn]="playerOnTurn"
    [isWinner]="isWinner"
    [isLoser]="isLoser"
    [isSkippingTurn]="isSkippingTurn"
    [shouldDraw]="shouldDraw"
    [playersCount]="playersCount"
    (nameChange)="nameChange.emit($event)"
  ></app-cards>
</div>
