// client/src/game/table/DeckCard.tsx
import React, { CSSProperties, FC, ReactElement, useMemo } from 'react'
import './DeckCard.css'
import { Card, getCardsAssetNumber, Suit } from '../../models/card'

interface Props {
    card: Card
    noTransform: boolean
    colorChangedTo?: Suit
}

export const DeckCard: FC<Props> = (props: Props): ReactElement => {
    return useMemo(() => {
        const getRandomArbitrary = (min: number, max: number) => {
            return Math.floor(Math.random() * Math.floor(max - min)) + min
        }

        const getRandomShift = (): CSSProperties => {
            return {
                position: 'absolute',
                transform: props.noTransform ? undefined : `translateX(${getRandomArbitrary(-10, 11)}px) translateY(${getRandomArbitrary(-5, 5)}px) rotate(${getRandomArbitrary(-60, 61)}deg)`,
            }
        }

        const getSuitIcon = (suit: Suit): ReactElement => {
            switch (suit) {
                case 'Ball':
                    return <img className="overlay-suit-icon" src="/suits/ball.svg" alt="balls"/>
                case 'Dick':
                    return <img className="overlay-suit-icon" src="/suits/dick.svg" alt="dicks"/>
                case 'Green':
                    return <img className="overlay-suit-icon" src="/suits/green.svg" alt="greens"/>
                case 'Heart':
                    return <img className="overlay-suit-icon" src="/suits/heart.svg" alt="hearts"/>
            }
        }

        return (
            <div className="deck-card-container">
                <div style={getRandomShift()}>
                    <img className="deck-card"
                         src={`/cards/${getCardsAssetNumber(props.card)}.png`}
                         alt={`${props.card.value} of ${props.card.suit}s`}/>
                    {props.colorChangedTo && <div className="color-overlay">{getSuitIcon(props.colorChangedTo)}</div>}
                </div>
            </div>
        )
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])
}

// client/src/app/game/components/table/deck-card/deck-card.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core'
import { Card, getCardsAssetNumber, Suit } from '../../../../models/card'
import { DomSanitizer, SafeStyle } from '@angular/platform-browser'
import { SettingsService } from '../../../../settings/settings.service'

@Component({
  selector: 'app-deck-card',
  templateUrl: './deck-card.component.html',
  styleUrls: ['./deck-card.component.scss'],
})
export class DeckCardComponent implements OnInit, OnChanges {
  @Input() readonly card?: Card
  @Input() readonly noTransform?: boolean
  @Input() readonly colorChangedTo?: Suit

  randomShift: string | null = null
  cardType = 'single-headed'
  cardBackground?: SafeStyle

  constructor(
    private sanitizer: DomSanitizer,
    private settingsService: SettingsService,
    ) {
    this.settingsService.getCardType().subscribe(type => this.cardType = type)
  }

  ngOnInit(): void {
    this.randomShift = this.getRandomShift()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.card
      && changes.card.previousValue?.suit !== changes.card.currentValue?.suit
      && changes.card.previousValue?.value !== changes.card.currentValue?.value
    ) {
      this.cardBackground = this.getCardUrl(changes.card.currentValue)
    }
  }

  getCardUrl(card: Card): SafeStyle {
    return this.sanitizer.bypassSecurityTrustStyle(`url("assets/cards/${this.cardType}/${getCardsAssetNumber(card)}.png")`)
  }

  /**
   * This function employs the Box–Muller transform to give a normal distribution between 0 and 1 inclusive.
   */
  private random_normal(): number {
    let u = 0, v = 0;
    while (u === 0) { u = Math.random(); } // Converting [0,1) to (0,1)
    while (v === 0) { v = Math.random(); }
    let num = Math.sqrt( -2.0 * Math.log( u ) ) * Math.cos( 2.0 * Math.PI * v );
    num = num / 10.0 + 0.5; // Translate to 0 -> 1
    if (num > 1 || num < 0) { return this.random_normal(); } // resample between 0 and 1
    return num;
  }

  private getRandomShift(): string | null {
    if (this.noTransform) { return null }

    const getRandomArbitrary = (min: number, max: number) => {
      const random = this.random_normal() * Math.floor(max - min) + min
      return Math.floor(random * 1.8) // flattens the curve
    }

    return `translateX(${getRandomArbitrary(-16, 40)}px) \
            translateY(${getRandomArbitrary(-24, 24)}px) \
            rotate(${getRandomArbitrary(-180, 180)}deg)`
  }
}

<div class="deck-card-container">
    <div *ngIf="card" [style.transform]="randomShift">
        <div class="deck-card" [style.background-image]="cardBackground"></div>
        <div *ngIf="colorChangedTo" class="color-overlay" [ngSwitch]="colorChangedTo">
            <img *ngSwitchCase="'Ball'" class="overlay-suit-icon" src="assets/suits/ball.svg" alt="balls"/>
            <img *ngSwitchCase="'Dick'" class="overlay-suit-icon" src="assets/suits/dick.svg" alt="dicks"/>
            <img *ngSwitchCase="'Green'" class="overlay-suit-icon" src="assets/suits/green.svg" alt="greens"/>
            <img *ngSwitchCase="'Heart'" class="overlay-suit-icon" src="assets/suits/heart.svg" alt="hearts"/>
        </div>
    </div>
</div>
