// client/src/app/game/components/players/players.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { Opponent } from '../../../models/opponent'
import { SettingsService } from '../../../settings/settings.service'

@Component({
  selector: 'app-players',
  templateUrl: './players.component.html',
  styleUrls: ['./players.component.scss'],
})
export class PlayersComponent implements OnInit {
  @Input() readonly players?: Opponent[]
  @Input() readonly gameActive?: boolean
  @Input() readonly playerOnTurn?: string
  @Input() readonly playerName?: string
  @Input() readonly participating?: boolean
  cardBack = '1'

  ngOnInit(): void {
    this.settingsService.getCardBack().subscribe(back => this.cardBack = back)
  }

  constructor(private settingsService: SettingsService) { }
}

<div id="players">
    <div *ngFor="let player of players" class="ion-padding-horizontal player-container" [id]="player.name">
        <div
                class="player-name"
                [attr.id]="player.name === playerOnTurn && gameActive ? 'playerOnTurn' : null">
            <ion-icon name="person"></ion-icon>
            <span class="player-text">{{player.name}}</span>
            <ion-badge *ngIf="player.name === playerName && participating" color="medium">me</ion-badge>
        </div>
        <div class="cards">
            <span *ngIf="player.place === 1" role="img" aria-label="first place">🥇</span>
            <span *ngIf="player.place === 2" role="img" aria-label="second place">🥈</span>
            <span *ngIf="player.place === 3" role="img" aria-label="third place">🥉</span>
            <span *ngIf="player.place > 3" role="img" aria-label="ta-da">🎉</span>
            <span *ngIf="player.loser" role="img" aria-label="loser">👎</span>
            <span *ngIf="gameActive">
                <img *ngFor="let card of [].constructor(player.cards)"
                     class="card-shell"
                     alt="card back"
                     [src]="'assets/cards/back/' + cardBack + '.svg'"
                />
            </span>
            <span *ngIf="(!player.place && !player.loser && (player.cards === 0 || !gameActive))">
                    <span role="img" aria-label="hourglass">⏳</span>
                    <span class="waiting">waiting...</span>
                </span>
        </div>
    </div>
    <div *ngIf="!players || players.length === 0" class="no-players">
        There are no players at this table
    </div>
</div>

// client/src/game/Players.tsx
import React, { FC, ReactElement } from 'react'
import './Players.css'
import { Grid } from '@material-ui/core'
import { Opponent } from '../models/opponent'
import PersonIcon from '@material-ui/icons/Person'

interface Props {
    players: Opponent[]
    gameActive: boolean
    playerOnTurn?: string
    playerName: string
    participating: boolean
}

export const Players: FC<Props> = (props: Props): ReactElement => {
    const getCard = (i: number): ReactElement => {
        return <img key={`${i}`} className="card-shell" src="/cards/0.png" alt="card back"/>
    }

    const getCardCount = (player: Opponent): ReactElement | undefined => {
        if (!props.gameActive && !props.players.some(player => player.place > 0)) return undefined

        if (player.place === 1) {
            return (
                <span role="img" aria-label="first place">🥇</span>
            )
        } else if (player.place === 2) {
            return (
                <span role="img" aria-label="second place">🥈</span>
            )
        } else if (player.place === 3) {
            return (
                <span role="img" aria-label="third place">🥉</span>
            )
        } else if (player.place > 3) {
            return (
                <span role="img" aria-label="ta-da">🎉</span>
            )
        } else if (player.loser) return (
            <span role="img" aria-label="loser">👎</span>
        )

        const cards: ReactElement[] = []
        for (let i = 0; i < player.cards; i++) cards.push(getCard(i))
        return (
            <span>{cards}</span>
        )
    }

    const generatePlayerTile = (player: Opponent): ReactElement => {
        return (
            <Grid item key={player.name}>
                <div className="player-container">
                    <div className="player-name"
                         id={player.name === props.playerOnTurn && props.gameActive ? 'playerOnTurn' : undefined}>
                        <PersonIcon/> {player.name}{player.name === props.playerName && props.participating && ' (you)'}
                    </div>
                    <div>
                        {getCardCount(player)}
                    </div>
                </div>
            </Grid>
        )
    }

    return (
        <Grid container spacing={2} justify="center">
            {props.players.map(generatePlayerTile)}
        </Grid>
    )
}
