// client-ionic/src/app/game/components/players/players.component.ts
import { Component, Input } from '@angular/core'
import { Opponent } from '../../models/opponent'

@Component({
  selector: 'app-players',
  templateUrl: './players.component.html',
  styleUrls: ['./players.component.scss'],
})
export class PlayersComponent {
  @Input() readonly players?: Opponent[]
  @Input() readonly gameActive?: boolean
  @Input() readonly playerOnTurn?: string
  @Input() readonly playerName?: string
  @Input() readonly participating?: boolean

  constructor() { }

}

<ion-grid>
    <ion-row class="ion-justify-content-center">
        <ion-col *ngFor="let player of players" class="ion-padding-horizontal player-container" size="auto">
            <div
                    class="player-name"
                    [attr.id]="player.name === playerOnTurn && gameActive ? 'playerOnTurn' : null">
                <ion-icon name="person"></ion-icon>
                <span class="player-text">{{player.name}}</span>
                <ion-badge *ngIf="player.name === playerName && participating" color="medium">you</ion-badge>
            </div>
            <div class="cards">
                <span *ngIf="player.place === 1" role="img" aria-label="first place">🥇</span>
                <span *ngIf="player.place === 2" role="img" aria-label="second place">🥈</span>
                <span *ngIf="player.place === 3" role="img" aria-label="third place">🥉</span>
                <span *ngIf="player.place > 3" role="img" aria-label="ta-da">🎉</span>
                <span *ngIf="player.loser" role="img" aria-label="loser">👎</span>
                <span *ngIf="gameActive">
                    <img *ngFor="let card of [].constructor(player.cards)" class="card-shell" src="assets/cards/0.svg"
                         alt="card back"/>
                </span>
            </div>
        </ion-col>
    </ion-row>
</ion-grid>

// client/src/game/Players.tsx
import React, { FC, ReactElement } from 'react'
import './Players.css'
import { Grid } from '@material-ui/core'
import { Opponent } from '../models/opponent'
import PersonIcon from '@material-ui/icons/Person'

interface Props {
    players: Opponent[]
    gameActive: boolean
    playerOnTurn?: string
    playerName: string
    participating: boolean
}

export const Players: FC<Props> = (props: Props): ReactElement => {
    const getCard = (i: number): ReactElement => {
        return <img key={`${i}`} className="card-shell" src="/cards/0.png" alt="card back"/>
    }

    const getCardCount = (player: Opponent): ReactElement | undefined => {
        if (!props.gameActive && !props.players.some(player => player.place > 0)) return undefined

        if (player.place === 1) {
            return (
                <span role="img" aria-label="first place">🥇</span>
            )
        } else if (player.place === 2) {
            return (
                <span role="img" aria-label="second place">🥈</span>
            )
        } else if (player.place === 3) {
            return (
                <span role="img" aria-label="third place">🥉</span>
            )
        } else if (player.place > 3) {
            return (
                <span role="img" aria-label="ta-da">🎉</span>
            )
        } else if (player.loser) return (
            <span role="img" aria-label="loser">👎</span>
        )

        const cards: ReactElement[] = []
        for (let i = 0; i < player.cards; i++) cards.push(getCard(i))
        return (
            <span>{cards}</span>
        )
    }

    const generatePlayerTile = (player: Opponent): ReactElement => {
        return (
            <Grid item key={player.name}>
                <div className="player-container">
                    <div className="player-name"
                         id={player.name === props.playerOnTurn && props.gameActive ? 'playerOnTurn' : undefined}>
                        <PersonIcon/> {player.name}{player.name === props.playerName && props.participating && ' (you)'}
                    </div>
                    <div>
                        {getCardCount(player)}
                    </div>
                </div>
            </Grid>
        )
    }

    return (
        <Grid container spacing={2} justify="center">
            {props.players.map(generatePlayerTile)}
        </Grid>
    )
}
