// client/src/game/table/DeckCard.tsx
import React, { CSSProperties, FC, ReactElement, useMemo } from 'react'
import './DeckCard.css'
import { Card, getCardsAssetNumber, Suit } from '../../models/card'

interface Props {
    card: Card
    noTransform: boolean
    colorChangedTo?: Suit
}

export const DeckCard: FC<Props> = (props: Props): ReactElement => {
    return useMemo(() => {
        const getRandomArbitrary = (min: number, max: number) => {
            return Math.floor(Math.random() * Math.floor(max - min)) + min
        }

        const getRandomShift = (): CSSProperties => {
            return {
                position: 'absolute',
                transform: props.noTransform ? undefined : `translateX(${getRandomArbitrary(-10, 11)}px) translateY(${getRandomArbitrary(-5, 5)}px) rotate(${getRandomArbitrary(-60, 61)}deg)`,
            }
        }

        const getSuitIcon = (suit: Suit): ReactElement => {
            switch (suit) {
                case 'Ball':
                    return <img className="overlay-suit-icon" src="/suits/ball.svg" alt="balls"/>
                case 'Dick':
                    return <img className="overlay-suit-icon" src="/suits/dick.svg" alt="dicks"/>
                case 'Green':
                    return <img className="overlay-suit-icon" src="/suits/green.svg" alt="greens"/>
                case 'Heart':
                    return <img className="overlay-suit-icon" src="/suits/heart.svg" alt="hearts"/>
            }
        }

        return (
            <div className="deck-card-container">
                <div style={getRandomShift()}>
                    <img className="deck-card"
                         src={`/cards/${getCardsAssetNumber(props.card)}.png`}
                         alt={`${props.card.value} of ${props.card.suit}s`}/>
                    {props.colorChangedTo && <div className="color-overlay">{getSuitIcon(props.colorChangedTo)}</div>}
                </div>
            </div>
        )
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])
}

// client-ionic/src/app/game/components/table/deck-card/deck-card.component.ts
import { Component, Input } from '@angular/core'
import { Card, getCardsAssetNumber, Suit } from '../../../models/card'

@Component({
  selector: 'app-deck-card',
  templateUrl: './deck-card.component.html',
  styleUrls: ['./deck-card.component.scss'],
})
export class DeckCardComponent {
  @Input() readonly card?: Card
  @Input() readonly noTransform?: boolean
  @Input() readonly colorChangedTo?: Suit

  constructor() { }

  getCardsAssetNumber(card: Card): string {
    return getCardsAssetNumber(card)
  }

  getRandomShift(): string | null {
    if (this.noTransform) { return null }

    const getRandomArbitrary = (min: number, max: number) => {
      return Math.floor(Math.random() * Math.floor(max - min)) + min
    }

    return `translateX(${getRandomArbitrary(-10, 11)}px) \
            translateY(${getRandomArbitrary(-5, 5)}px) \
            rotate(${getRandomArbitrary(-60, 61)}deg)`
  }
}

<div class="color-overlay-container">
    <div *ngIf="card" [style.transform]="getRandomShift()">
        <!--        TODO better alt/image as background -->
        <!--        TODO match card size 100px -->
        <img class="deck-card"
             [src]="'assets/cards/' + getCardsAssetNumber(card) + '.png'"
             alt="card.value + card.suit"
        />
        <!-- TODO test if works -->
        <div *ngIf="colorChangedTo" class="color-overlay" [ngSwitch]="colorChangedTo">
            <img *ngSwitchCase="'Ball'" class="overlay-suit-icon" src="assets/suits/ball.svg" alt="balls"/>
            <img *ngSwitchCase="'Dick'" class="overlay-suit-icon" src="assets/suits/dick.svg" alt="dicks"/>
            <img *ngSwitchCase="'Green'" class="overlay-suit-icon" src="assets/suits/green.svg" alt="greens"/>
            <img *ngSwitchCase="'Heart'" class="overlay-suit-icon" src="assets/suits/heart.svg" alt="hearts"/>
        </div>
    </div>
</div>
